### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by smmsadrnezh** [ComboStrap/combo#33]
I'm using PHP 7.4 on my server, and I have Dokuwiki "Igor" RC2. Still, after installing the combo plugin, I see an error like this in apache logs, and I can't open my website unless I remove the combo plugin directory on the server:

`AH01071: Got error 'PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /lib/plugins/combo/ComboStrap/LogUtility.php on line 204PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /inc/ErrorHandler.php on line 89', referer:`

I also disabled all my other plugins, and it didn't help. I can test changing the code on my server if it helps to find the problem.

**Comment by gerardnico** [comment]
Agreed. 

The difficulty here is that it's hard to test.

The best should be that we also deliver the dependencies (xml, ...) but php does not allow that.

**Comment by gerardnico** [comment]
Note that the last dokuwiki version is not yet validated against combo.

**Comment by gerardnico** [comment]
The doc is here by the way for a raw server:

https://combostrap.com/support/combostrap-platform-requirements-956axulc#moduleextension

**Comment by gerardnico** [comment]
Thanks appreciated.

We do it and we report the problem. 

The error that you got is because the reporting was creating a loop in the code until you got no memory. 
This is what I refer to when I said that this is difficult to test (the consequences are pretty difficult to know and creating a test environment for each dependencies that is missing is quasi a no go)

The code that you point out is modified in the next release to avoid this cycle.

https://github.com/ComboStrap/combo/blob/1.25/ComboStrap/PluginUtility.php#L504

Do you have any other questions ?

**Comment by gerardnico** [comment]
To be specific, we send a message with a logo. This logo is a svg.

The code was asking to reduce the svg width to an icon width (16) Reducing the width means that the code uses the xml extension.

The xml extension not being there, the code reducing the size was sending a message with the logo (and here you have the loop). 

The logo send does not reduce anymore. We have killed the loop.
