### ISSUE TITLE
TOC Appears twice in ?do=admin&page=config

### ISSUE THREAD

**Issue by listerr** [ComboStrap/combo#41]
When I go to the admin -> config settings page, I now get the TOC appearing twice.

It doesn't do this on other pages in the admin section e.g. Extension Manager, only the Configuration Settings page.

If I disable the combo extension, only one TOC is produced.

Rob

**Comment by gerardnico** [comment]
Sorry for that.
I don't have that on my test machine.
(May be a igor things)

Admin page are rendered differently in Dokuwiki. The TOC may be used for admin page (ie SQLITE) and HTML page. That's why in the next release we don't use use any template anymore (we work with the dokuwiki template if we don't render a HTML page)

**Comment by gerardnico** [comment]
Sorry but even on Igor, I don't get the same behavior.

**Comment by gerardnico** [comment]
hi rob, thanks again.
I'm cleaning a little bit. If this problem is still open, don't hesitate to reopen.
In the next version, because we don't take anymore a new template, it should not appear anymore
